Repository SwEnt-Project-G18/SwEntApp, pull requests merged in 2024-04, with the labels that each got.

#13 Login authentication and Navigation setup
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ui/LoginScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/WelcomeScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/authentication/SignInState.kt
  app/src/main/java/com/github/se/gomeet/model/repository/AuthRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/create/Create.kt
  app/src/main/java/com/github/se/gomeet/ui/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/explore/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/ui/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Color.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
  app/src/main/java/com/github/se/gomeet/ui/trending/Trends.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/AuthViewModel.kt
  app/src/main/res/drawable/gomeet_logo.xml
  app/src/main/res/drawable/gomeet_text.xml
  app/src/main/res/drawable/google_logo.xml
  app/src/main/res/font/roboto.xml
  app/src/main/res/font/robotolight.ttf
  gradlew.bat
  secrets.defaults.properties
Labels: enhancement

#14 Map
  app/build.gradle.kts
  app/src/main/java/com/github/se/gomeet/ui/explore/Explore.kt
Labels: enhancement

#18 S3 CreateEvent UI optimisation
  app/src/main/java/com/github/se/gomeet/EventFirebaseConnection.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/Create.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/PrivateCreate.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Color.kt
  app/src/main/res/drawable/arrow_trending.xml
Labels: enhancement

#22 S3 display events on map
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/main/java/com/github/se/gomeet/EventFirebaseConnection.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Labels: enhancement

#26 S3 Event Creation Image Feature and UI Enhancements
  app/build.gradle.kts
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/Create.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Color.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Labels: enhancement

#25 Sprint 3: adding authentication tests and more UI tests
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/github/se/gomeet/KaspressoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/LoginScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/RegisterScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/WelcomeScreenTest.kt
  app/src/main/java/com/github/se/gomeet/model/repository/AuthRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/test/java/com/github/se/gomeet/ExampleUnitTest.kt
  app/src/test/java/com/github/se/gomeet/model/repository/AuthTests.kt
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#23 S3 UI profile
  .gitignore
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ui/profile/ProfileTest.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Profile.kt
  app/src/main/res/drawable/chess_demo.webp
  build.gradle.kts
Labels: enhancement

#49 S4 follower database connection + view model + tests
  app/src/androidTest/java/com/github/se/gomeet/KaspressoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/MainActivityTest.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/LoginScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/RegisterScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/WelcomeScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/TrendsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/UserFirebaseConnection.kt
  app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement, tests, finished

#51 S5 Event Info Screen UI Implementation
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/res/drawable/baseline_chat_bubble_outline_24.xml
  app/src/main/res/drawable/heart.xml
Labels: ui

#52 S5 search bar
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/res/drawable/gomeet_icon.xml
  app/src/main/res/drawable/mic_icon.xml
Labels: enhancement, ui

#57 S5 fix merge issues
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
Labels: fix

#55 S5 display current location on map
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/res/drawable/location_icon.xml
Labels: enhancement

#66 s5 ui adjustments
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
Labels: fix, ui

#72 S5 Messaging
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/RegisterScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, done

#70 S5 location suggestions
  app/src/androidTest/java/com/github/se/gomeet/screens/CreateEventScreen.kt
  app/src/androidTest/java/com/github/se/gomeet/screens/CreateScreen.kt
  app/src/androidTest/java/com/github/se/gomeet/screens/LoginScreen.kt
  app/src/androidTest/java/com/github/se/gomeet/screens/TrendsScreen.kt
  app/src/androidTest/java/com/github/se/gomeet/screens/WelcomeScreenScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Labels: enhancement

#75 Profile settings screen
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ProfileSettingsTest.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/SettingsScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/res/drawable/arrow_back.xml
  app/src/main/res/drawable/check_icon.xml
  app/src/main/res/drawable/folder.xml
  app/src/main/res/drawable/indeterminate_check_box.xml
  app/src/main/res/drawable/language.xml
  app/src/main/res/drawable/mail.xml
  app/src/main/res/drawable/mobile_friendly.xml
  app/src/main/res/drawable/navigate_next.xml
  app/src/main/res/drawable/star.xml
Labels: enhancement

#71 Custom Pins for Map Events
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/gomeet/Application.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CustomPins.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/res/drawable/date_background_shape.png
  app/src/main/res/drawable/default_pin.png
  app/src/main/res/layout/custom_pin_layout.xml
Labels: enhancement

#83 Documentation of the app
  app/src/androidTest/java/com/github/se/gomeet/MainActivityTest.kt
  app/src/main/java/com/github/se/gomeet/Application.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/UserFirebaseConnection.kt
  app/src/main/java/com/github/se/gomeet/authentication/SignInState.kt
  app/src/main/java/com/github/se/gomeet/model/event/Event.kt
  app/src/main/java/com/github/se/gomeet/model/event/EventList.kt
  app/src/main/java/com/github/se/gomeet/model/event/Invite.kt
  app/src/main/java/com/github/se/gomeet/model/event/location/Location.kt
  app/src/main/java/com/github/se/gomeet/model/repository/AuthRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/InvitesRepository.kt
  app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/AddParticipants.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/Create.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CustomPins.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/SettingsScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/AuthViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventInviteViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: documentation

#82 Join Events, Add to Favorites
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/EventInfoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/TrendsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt
  app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
  app/src/main/res/drawable/edit.xml
  app/src/main/res/drawable/redheart.xml
Labels: enhancement, done
