Repository SwEnt-Project-G18/SwEntApp, pull requests merged in 2024-05, with the labels that each got.

#94 Logic for the EditProfile synchronized with Firebase
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement

#102 s6 improve coverage
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/AddParticipantsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt
Labels: tests

#117 Manage the invitations from EventInfo
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/AddParticipantsTest.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/model/event/Invite.kt
  app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/AddParticipants.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventInviteViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement

#124 S7-ChannelList
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
Labels: enhancement

#126 Firebase caching implementation
  app/src/androidTest/java/com/github/se/gomeet/InstrTestRunner.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/RegisterScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/TrendsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventInfoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/InvitesRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Followers.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Following.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventInviteViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement

#127 s7 tags
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/androidTest/java/com/github/se/gomeet/model/TagTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventInfoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/model/Tag.kt
  app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt
  app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement

#137 S7 Permission Screen implementation (+ Help and About Screen)
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileSettingsTest.kt
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsAbout.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsHelp.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsPermissions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
Labels: enhancement

#151 Trends Screen UI improvement
  app/build.gradle.kts
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
Labels: enhancement, ui

#163 Added date and time picker in create event screen + displaying event time
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventInfoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventListTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/model/event/Event.kt
  app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/DateTimePicker.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Labels: documentation, enhancement, ui

#156 Notifications implementation
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/NotificationsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: documentation, enhancement, ui, ViewModel

#154 s8 ui adjustments
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/LoginScreenTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsScreenTest.kt
  app/src/main/java/com/github/se/gomeet/model/Tag.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterNameCountryPhone.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/DateTimePicker.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/FollowingFollowers.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
Labels: done, ui

#168 S8 more tests
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd3.kt
  app/src/androidTest/java/com/github/se/gomeet/screens/ManageInvitesScreen.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriendTest.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriend.kt
Labels: tests

#182 S8 Code refactor (1)
  app/src/androidTest/java/com/github/se/gomeet/InstrTestRunner.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd3.kt
  app/src/androidTest/java/com/github/se/gomeet/model/repository/AuthRepositoryTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/TrendsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventInfoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriendTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/NotificationsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventListTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventInvitationViewModelTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/MainActivity.kt
  app/src/main/java/com/github/se/gomeet/model/authentication/SignInState.kt
  app/src/main/java/com/github/se/gomeet/model/event/Event.kt
  app/src/main/java/com/github/se/gomeet/model/event/Invitation.kt
  app/src/main/java/com/github/se/gomeet/model/repository/AuthRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterNameCountryPhone.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterUsernameEmail.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/LoadingText.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/Create.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CustomPins.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/AddParticipants.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriend.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/FollowingFollowers.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/AuthViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
  database.rules.json
  firebase.json
Labels: documentation, fix, ui, ViewModel, Model

#185 fixed test
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
Labels: tests, fix

#192 S7 trends algo
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/NotificationsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/model/Tag.kt
  app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/SearchModule.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement, fix, ViewModel

#203 S9 App Logo Change
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/SearchModule.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/res/drawable/gomeet_icon.xml
  app/src/main/res/drawable/gomeet_logo.xml
  app/src/main/res/drawable/gomeet_text.xml
  app/src/main/res/mipmap-anydpi-v26/gomeet_logo.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/gomeet_logo.png
  app/src/main/res/mipmap-hdpi/gomeet_logo_background.png
  app/src/main/res/mipmap-hdpi/gomeet_logo_foreground.png
  app/src/main/res/mipmap-hdpi/gomeet_logo_monochrome.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/gomeet_logo.png
  app/src/main/res/mipmap-mdpi/gomeet_logo_background.png
  app/src/main/res/mipmap-mdpi/gomeet_logo_foreground.png
  app/src/main/res/mipmap-mdpi/gomeet_logo_monochrome.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/gomeet_logo.png
  app/src/main/res/mipmap-xhdpi/gomeet_logo_background.png
  app/src/main/res/mipmap-xhdpi/gomeet_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/gomeet_logo_monochrome.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/gomeet_logo.png
  app/src/main/res/mipmap-xxhdpi/gomeet_logo_background.png
  app/src/main/res/mipmap-xxhdpi/gomeet_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/gomeet_logo_monochrome.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/gomeet_logo.png
  app/src/main/res/mipmap-xxxhdpi/gomeet_logo_background.png
  app/src/main/res/mipmap-xxxhdpi/gomeet_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/gomeet_logo_monochrome.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement, ui

#204 Edit Event Screen implementation
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EditEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
Labels: enhancement, ui

#211 s9 fix some issues
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterNameCountryPhone.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterPassword.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterPfp.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterUsernameEmail.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/DateTimePicker.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/LoadingText.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/SearchModule.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/Create.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EditEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/manageinvites/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/manageinvites/UserInviteWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/TopTitleExplore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriend.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriendUserItem.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/FollowingFollowers.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsAbout.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsHelp.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsPermissions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/settings/SettingsScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Color.kt
  app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt
Labels: fix

#210 S9 Update Map Visuals and Custom Pin to Match App Theme
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/res/drawable/date_background_shape.png
  app/src/main/res/drawable/default_pin.png
  app/src/main/res/raw/map_style_dark.json
  app/src/main/res/raw/map_style_light.json
Labels: enhancement, ui

#217 S9 Share profile and event & scanner screen UI
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/QRCodeScannerScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/res/drawable/scan_icon.xml
  app/src/main/res/xml/file_paths.xml
Labels: enhancement, ui

#230 S9 QR Logic and Sharing Enhancements
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/QRCodeScannerScreen.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/QRViewModel.kt
  app/src/main/res/drawable/add_friend.xml
  app/src/main/res/drawable/download_icon.xml
  app/src/main/res/drawable/share_icon.xml
  app/src/main/res/drawable/upload_icon.xml
Labels: enhancement, ui

#238 Added event and user ratings
  app/src/androidTest/java/com/github/se/gomeet/InstrTestRunner.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd3.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/TrendsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventInfoTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriendTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/NotificationsTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventListTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileTest.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt
  app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/model/event/Event.kt
  app/src/main/java/com/github/se/gomeet/model/event/location/Location.kt
  app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt
  app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt
  app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterScreen.kt
  app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterUsernameEmail.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/SearchModule.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/AddParticipants.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/manageinvites/ManageInvites.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/manageinvites/UserInviteWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/posts/EventPost.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/ColumnContentExplore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/Explore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/GoogleMapExplore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/RowContentExplore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/FollowingFollowers.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/QRViewModel.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Labels: enhancement, done, ui, ViewModel, Firebase

#242 Add Participants screen implementation
  app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt
  app/src/androidTest/java/com/github/se/gomeet/screens/ManageInvitesScreen.kt
  app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/AddParticipants.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Labels: documentation, enhancement, ui, ViewModel

#254 Fixed bug where users could delete events for which they were not the creator
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
Labels: fix

#256 s10 url
  app/src/main/java/com/github/se/gomeet/InitFunctions.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/SearchModule.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/MyEventInfo.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/GoogleMapExplore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/RowContentExplore.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/notifications/InvitationNotificationWidget.kt
  app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt
  app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
  app/src/main/java/com/github/se/gomeet/viewmodel/QRViewModel.kt
Labels: enhancement
